### ISSUE TITLE
Rare but possible crash

### ISSUE THREAD

**Issue by JNechaevsky** [Russian-Doom/russian-doom#272]
It is possible to catch on NUTS.wad while walking with iddqd/idclip in random direction.

```
Thread 1 received signal SIGSEGV, Segmentation fault.
0x00007ff73978aa72 in R_DrawColumn () at r_draw.c:156
156                 *dest = dc_colormap[dc_source[frac>>FRACBITS]];

(gdb) p frac
$1 = <optimized out>

(gdb) p dc_source
$2 = (byte *) 0xb964 <error: Cannot access memory at address 0xb964>

(gdb) p dc_colormap
$3 = (lighttable_t *) 0x17a64f16280 ""

(gdb) bt

#0  0x00007ff73978aa72 in R_DrawColumn () at r_draw.c:156
#1  0x00007ff73978f8f2 in R_DrawPlanes () at r_plane.c:397
#2  0x00007ff73978edef in R_RenderPlayerView (player=0x7ff73993c480 <players>)
    at r_main.c:1011
#3  0x00007ff73975554f in D_Display () at d_main.c:487
#4  D_Display () at d_main.c:395
#5  0x00007ff7397560c1 in D_DoomLoop () at d_main.c:895
#6  0x00007ff7397596e6 in D_DoomMain () at d_main.c:3193
#7  0x00007ff73975372e in SDL_main (argc=<optimized out>,
    argv=<optimized out>) at i_main.c:132
#8  0x00007ff7397325ba in main_getcmdline ()
#9  0x00007ff7397313b1 in __tmainCRTStartup ()
    at C:/_/M/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:321
#10 0x00007ff7397314c6 in WinMainCRTStartup ()
    at C:/_/M/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:176
```

That's something odd. Could it be same to I've got some time ago in https://github.com/fabiangreffrath/crispy-doom/issues/730#issuecomment-813047733 ?
Something wrong with updated `R_GetColumn`, since `dc_source = R_GetColumn(skytexture, angle);`? 

@fabiangreffrath, maybe you have any suspicions?

**Comment by JNechaevsky** [comment]
Nope, fortunately I was wrong, it not related to https://github.com/fabiangreffrath/crispy-doom/commit/4ddfacb2e4a415413ae66471ea0480697afdb61d, even after rolling back previous implementations crash may happen. Really odd and not clear what/why/where the reason of corruption.

I wonder if it will help to separate sky drawing into own function, just like in Heretic.

**Comment by JNechaevsky** [comment]
Fixed in https://github.com/JNechaevsky/russian-doom/commit/eb110ef67a4068525471a89653e34d18693086ba. God knows what is happened and what was wrong.
